# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5b562fa89aa5d4aad7d0789fa943e66e75089d763cce6ed7e99f57d462d4ac16cec3f3cfe24ec8b7e2051b42d70d456da2039a4c6b70474f5a49ad3888a4238

test:
  secret_key_base: b49b9a3044c022cf28a59a693b727f6035612a5357ce7a8ae80f5781733d40a041077ae7f95c4c0aa52b8b06695f7a8c4dbe9b518864c9f588789a5408fb839b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
